cmake_minimum_required(VERSION 3.20)
project(lingo LANGUAGES CXX)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")

add_subdirectory(lingo-core lingo-core)
add_subdirectory(lingo-desktop/editor lingo-editor)
add_subdirectory(lingo-desktop/service lingo-service)
add_subdirectory(lingo-desktop lingo-desktop)
